### PR TITLE
split values of nowcast(s)

### PR DESCRIPTION
**Pull request by juan-carlos-tsb**
For the visualization it is necessary to split the values.

### CODE REVIEW

**Comment by juan-carlos-tsb** [comment]
With commented out code for comparison. Feel free to remove comments.

**Comment by ff6347** [comment]
To make the tileset more humanreadable I changed the naming from 1,2,3,4
to their explicit naming. @vogelino @dnsos Is this okay for you?
or should use just numbers?

**Comment by vogelino** [comment]
> To make the tileset more humanreadable I changed the naming from 1,2,3,4 to their explicit naming. @vogelino @dnsos Is this okay for you? or should we use just numbers?

I'm not sure of which naming you're taking about. Do these name changes have an implication on the frontend?

**Pull request merged**
